name: macos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: silicon-binaries
      run: git clone https://github.com/ColleagueRiley/Silicon -b binaries silicon-binaries
    - name: gcc
      run: gcc main.c -I./Silicon/include silicon-binaries/ARM/*.o -framework AppKit -ISilicon/include -framework OpenGL -framework CoreVideo -std=c99
