name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: gcc
      run: gcc -I./ ./examples/basic/main.c -lopengl32 -lshell32 -lgdi32
